# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  high_level_summary: false
  poem: false
  enable_prompt_for_ai_agents: true
  auto_review:
    auto_incremental_review: false
